version: '2'

services:
    xhgui:
        image: dvdche/xhgui
        container_name: xhgui
        hostname: xhgui
        network_mode: bridge
        volumes: 
            - .vol/www:/var/www/
            - .vol/data:/data/
        ports: 
            - 8080:80
        tty: true
        hostname: xhgui
        build:
            context: .
            dockerfile: dockerfile

